### ISSUE TITLE
java.lang.ClassNotFoundException at com.playseeds.unity3d.androidbridge.InAppMessageShowCountListenerBridge

### ISSUE THREAD

**Issue by NitinParmar7** [therealseeds/seeds-sdk-unity#3]
I am getting this error 
java.lang.ClassNotFoundException: com.playseeds.unity3d.androidbridge.InAppMessageShowCountListenerBridge
I/Unity   (26340):  at java.lang.Class.classForName(Native Method)
I/Unity   (26340):  at java.lang.Class.forName(Class.java:251)
I/Unity   (26340):  at java.lang.Class.forName(Class.java:216)
I/Unity   (26340):  at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
I/Unity   (26340):  at com.unity3d.player.UnityPlayer.a(Unknown Source)
I/Unity   (26340):  at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
I/Unity   (26340): Caused by: java.lang.NoClassDefFoundError: com/playseeds/unity3d/androidbridge/InAppMessageShowCountListenerBridge
I/Unity   (26340):  ... 6 more
I/Unity   (26340): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.playseeds.unity3d.androidbridge.InAppMessageShowCountListenerBridge" on path: DexPathList[[zip file "/data/app/com.migoi.transmission-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.migoi.transmission-1, /vendor/lib, /system/lib]]

any solution for it

**Comment by attekei** [comment]
Hi @NitinParmar7, thanks for the bug report! 

I wasn't able to immediately reproduce the issue. Are you using the latest version of the Unity SDK (0.4.1)? You can download it from [the docs page](http://developers.playseeds.com/docs/unity-sdk-setup). 

And which Unity version are you using?
